/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email 註冊 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 註冊成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email 已被註冊 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "ok": false,
                         *       "error": {
                         *         "code": "USER_EXISTS",
                         *         "message": "Email already registered"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email 密碼登入 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登入成功（若啟用 2FA 會回 202 並需呼叫 /auth/2fa/verify） */
                200: {
                    headers: {
                        /** @description refresh_token (httpOnly, Secure, SameSite=Strict, 30 days) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                /** @description 已驗證主要憑證，等待 2FA code */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            ok?: false;
                            error?: {
                                /** @constant */
                                code?: "TWO_FA_REQUIRED";
                                /** Format: uuid */
                                challenge_id?: string;
                            };
                        };
                    };
                };
                /** @description 帳密錯誤 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "ok": false,
                         *       "error": {
                         *         "code": "INVALID_CREDENTIALS",
                         *         "message": ""
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description 暴力登入鎖定（15 分鐘） */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google OAuth 登入 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Google ID token from One Tap */
                        id_token: string;
                        /** @description CSRF state token issued by FE */
                        state: string;
                    };
                };
            };
            responses: {
                /** @description 登入成功（新使用者自動建立） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                /** @description state mismatch 或 id_token 無效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 refresh cookie 換新 access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie: {
                    refresh_token: string;
                };
            };
            requestBody?: never;
            responses: {
                /** @description 新的 access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            ok?: true;
                            data?: {
                                access_token?: string;
                                /** @description seconds */
                                expires_in?: number;
                            };
                        };
                    };
                };
                /** @description refresh 無效或被撤銷 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤銷 refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已登出 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 啟用 2FA，回 TOTP secret 與 QR */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description enrollment payload */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            ok?: true;
                            data?: {
                                /** @description base32 TOTP secret */
                                secret?: string;
                                /** @description data:image/png;base64,... */
                                qr_data?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 驗證 TOTP code（首次啟用或登入時帶 challenge_id） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        /**
                         * Format: uuid
                         * @description 登入流程才需要
                         */
                        challenge_id?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthSuccess"];
                    };
                };
                /** @description code 錯誤 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得本人資訊 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            ok?: true;
                            data?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/setup-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 建立 Stripe SetupIntent 用以綁卡 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description client_secret 回給 FE 用 Stripe Elements */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            ok?: true;
                            data?: {
                                client_secret?: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook receiver
         * @description 以 `event.id` 作 idempotency key。
         *     必須驗證 `Stripe-Signature` header。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Stripe-Signature": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Accepted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Signature 驗證失敗 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出本人綁定卡片 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description methods */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            ok?: true;
                            data?: components["schemas"]["PaymentMethod"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/methods/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 解除綁定一張卡 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 此 method 不存在或不屬於該使用者 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * KPI 卡片數據（本期值、比較期值、變化率、sparkline）
         * @description specs/dashboard-kpi.md §7.1。金額以「元」回傳。
         */
        get: {
            parameters: {
                query: {
                    /** @description 本期起日 (YYYY-MM-DD */
                    from: string;
                    /** @description 本期迄日（含） */
                    to: string;
                    /** @description 比較期起日（省略則自動 WoW） */
                    compareFrom?: string;
                    /** @description 比較期迄日 */
                    compareTo?: string;
                    /** @description 逗號分隔；省略=全部 */
                    brands?: string;
                    granularity?: "day" | "week" | "month";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description KPI 數據 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KpiResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 未授權 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 折線圖時間序列
         * @description specs/dashboard-kpi.md §7.2。回逐桶的指標值。
         */
        get: {
            parameters: {
                query: {
                    from: string;
                    to: string;
                    brands?: string;
                    granularity?: "day" | "week" | "month";
                    /** @description 逗號分隔；省略=全部 */
                    metrics?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 時間序列 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TimeseriesResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 未授權 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** @description 至少 10 字，含英數 */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthSuccess: {
            /** @constant */
            ok?: true;
            data?: {
                access_token?: string;
                expires_in?: number;
                user?: components["schemas"]["User"];
            };
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            two_fa_enabled?: boolean;
            has_payment_method?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        PaymentMethod: {
            /** Format: uuid */
            id?: string;
            /** @example visa */
            brand?: string;
            /** @example 4242 */
            last4?: string;
            /** @example 12 */
            exp_month?: number;
            /** @example 2029 */
            exp_year?: number;
            is_default?: boolean;
        };
        Error: {
            /** @constant */
            ok: false;
            error: {
                /** @example WEAK_PASSWORD */
                code: string;
                message: string;
            };
        };
        DateRange: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
        };
        /** @description 單一 KPI 的本期值、比較期值、變化率與 sparkline */
        KpiCell: {
            /** @description 本期值（金額為元，margin 為百分比） */
            value?: number;
            /** @description 比較期值 */
            compare?: number;
            /** @description 變化率（%）；比較期為 0 時為 null */
            changePct?: number | null;
            /** @description 本期逐桶走勢 */
            spark?: number[];
        };
        KpiResponse: {
            /** @constant */
            ok?: true;
            data?: {
                /**
                 * @description 資料來源標示（demo 為 seed 假資料）
                 * @example seed
                 */
                source?: string;
                /** @enum {string} */
                granularity?: "day" | "week" | "month";
                period?: components["schemas"]["DateRange"];
                compare?: components["schemas"]["DateRange"];
                /** @description 7 個 KPI，key 為指標名 */
                kpis?: {
                    wager?: components["schemas"]["KpiCell"];
                    validWager?: components["schemas"]["KpiCell"];
                    ggr?: components["schemas"]["KpiCell"];
                    margin?: components["schemas"]["KpiCell"];
                    playerCount?: components["schemas"]["KpiCell"];
                    betCount?: components["schemas"]["KpiCell"];
                    atppu?: components["schemas"]["KpiCell"];
                };
            };
        };
        TimeseriesResponse: {
            /** @constant */
            ok?: true;
            data?: {
                /** @example seed */
                source?: string;
                /** @enum {string} */
                granularity?: "day" | "week" | "month";
                period?: components["schemas"]["DateRange"];
                metrics?: string[];
                points?: ({
                    /** @description 日期或月份 key */
                    bucket?: string;
                } & {
                    [key: string]: number;
                })[];
            };
        };
    };
    responses: {
        /** @description 輸入驗證失敗 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
